// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/linn-phyo/go_gin_clean_architecture/src/api/handler"
	"github.com/linn-phyo/go_gin_clean_architecture/src/repository"
	"github.com/linn-phyo/go_gin_clean_architecture/src/usecase"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeUsersAPI(DB *gorm.DB) (*handler.UserHandler, error) {
	userRepository := repository.NewUserRepository(DB)
	userUseCase := usecase.NewUserUseCase(userRepository)
	userHandler := handler.NewUserHandler(userUseCase)
	return userHandler, nil
}
